GAAMATCH_MODE = 1
SPORTSCODE_MODE = 2
GAAMATCH_MODE_PREFIX = 'GM'
SPORTSCODE_MODE_PREFIX = 'SC'
SPORTSCODE_MODE_UNKNOWN = 'TBD'
MODES = [GAAMATCH_MODE, SPORTSCODE_MODE]

def getPrefix(mode):
    if mode == GAAMATCH_MODE:
        return GAAMATCH_MODE_PREFIX
    elif mode == SPORTSCODE_MODE:
        return SPORTSCODE_MODE_PREFIX
    else:
        return SPORTSCODE_MODE_UNKNOWN